publisher:
  name: My new publisher name
  description:
    en-US: >
      A lot of extra information about my wonderful publisher
  website: https://solanamobile.com
  email: hello@solanamobile.com

app:
  name: My new app name
  description:
    en-US: >
      My new app description
  creators:
    - 7pF18kRbv4mWdLPNMa8CjqLotQpznxzzRJqwdMibMitE
  license_url: http://cdn.org/license.html
  copyright_url: http://cdn.org/copyright.html
  privacy_policy_url: http://cdn.org/privacy.html
  age_rating: 3+
  locales:
    - en-US
    - ja-JP
    - it-IT
  android_details:
    android_package: com.company.dapp
    google_store_package: com.company.dapp.otherpkg
    min_sdk: 21
    version_code: 5
    permissions:
      - android.permission.INTERNET
      - android.permission.LOCATION_HARDWARE
      - com.solanamobile.seedvault.ACCESS_SEED_VAULT
