publisher:
  name: This is an example!
  publicKey: <some-public-key>
  description: |
    This is a multi-line string that can be used to express
    how wonderful this publisher is
apps:
  - name: My first wonderful application!
    description: |
      A long description describing this application
    android_package: com.solanamobile.foo
